/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Otp
         * @description Gửi OTP qua Zalo/SMS. Trả về số giây phải chờ trước khi cho gửi lại.
         */
        post: operations["request_otp_auth_otp_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp */
        post: operations["verify_otp_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Up
         * @description Tạo user + gửi OTP. Xác nhận OTP ở `/auth/otp/verify` mới nhận được token.
         *
         *     (Trả `TokenPair` ngay ở bước này là sai — sẽ cấp token cho số điện thoại
         *     chưa được xác minh sở hữu.)
         */
        post: operations["sign_up_auth_sign_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Email
         * @description Đường phụ — chỉ dùng khi user đã thêm email/mật khẩu trong Cài đặt.
         */
        post: operations["login_email_auth_login_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_workspaces_get"];
        put?: never;
        /**
         * Create Workspace
         * @description Bước 1 Onboarding: chọn ngành rồi tạo tiệm.
         *
         *     Tự set làm `active_workspace_id` — JWT hiện tại của client chưa phản ánh
         *     điều này, gọi `/auth/refresh` (hoặc `/workspaces/{id}/activate`) ngay sau
         *     để lấy token mới.
         */
        post: operations["create_workspace_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Workspace
         * @description Đổi tên, ngành, hoặc toggle "Chế độ đăng bài" (review_first | full_auto).
         */
        patch: operations["update_workspace_workspaces__workspace_id__patch"];
        trace?: never;
    };
    "/workspaces/{workspace_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Workspace
         * @description Đổi `active_workspace_id` trong JWT — màn "Chọn tiệm".
         */
        post: operations["activate_workspace_workspaces__workspace_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_workspaces__workspace_id__members_get"];
        put?: never;
        /** Invite Member */
        post: operations["invite_member_workspaces__workspace_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_workspaces__workspace_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brand Profile */
        get: operations["get_brand_profile_brand_profile_get"];
        /**
         * Update Brand Profile
         * @description Ghi xong phải invalidate cache profile của tenant để worker đọc bản mới.
         */
        put: operations["update_brand_profile_brand_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media */
        get: operations["list_media_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/upload-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload Ticket
         * @description Cấp presigned URL. Client PUT thẳng lên storage, không đi qua API.
         */
        post: operations["create_upload_ticket_media_upload_ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Media */
        patch: operations["update_media_media__asset_id__patch"];
        trace?: never;
    };
    "/content/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Content Job
         * @description Nút "Để Havi viết cho chị".
         *
         *     Đẩy 1 job vào hàng đợi; worker gọi LLM đúng 1 lần và sinh 4-5 bản theo kênh.
         *     API trả ngay `queued`, frontend poll `GET /content/jobs/{id}` cho tới `drafts_ready`.
         */
        post: operations["create_content_job_content_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content Job */
        get: operations["get_content_job_content_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Content
         * @description `status=pending_approval` chính là màn Hàng chờ duyệt.
         */
        get: operations["list_content_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["get_content_content__content_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Content
         * @description Sửa text tạo `content_item_version` mới, không ghi đè bản cũ.
         */
        patch: operations["update_content_content__content_id__patch"];
        trace?: never;
    };
    "/content/{content_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_content__content_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{content_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Content
         * @description Duyệt lẻ 1 bài: pending_approval → approved → scheduled.
         *
         *     Trả 409 nếu trạng thái hiện tại không cho phép (xem core.content_state).
         */
        post: operations["approve_content_content__content_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/{content_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Content
         * @description Từ chối: pending_approval → draft.
         */
        post: operations["reject_content_content__content_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/approve-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve All
         * @description Nút "Duyệt & đăng hết" — bài nào không duyệt được thì báo lý do, không fail cả lô.
         */
        post: operations["approve_all_content_approve_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/{content_id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reschedule
         * @description Kéo-thả đổi giờ đăng. Chỉ cho `approved` / `scheduled`; `published` trả 409.
         */
        post: operations["reschedule_calendar__content_id__reschedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Connections
         * @description Bước 2 Onboarding + trang Cài đặt: chấm xanh/đỏ theo `status`.
         */
        get: operations["list_connections_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{platform}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Oauth */
        post: operations["start_oauth_connections__platform__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{platform}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Callback */
        get: operations["oauth_callback_connections__platform__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{platform}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect */
        delete: operations["disconnect_connections__platform__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inbox */
        get: operations["list_inbox_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/{item_id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Reply
         * @description Nút "Gửi" / "Sửa rồi gửi" — chỉ chạy khi có action của người thật.
         */
        post: operations["send_reply_inbox__item_id__reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/{item_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss
         * @description Nút "Bỏ qua".
         */
        post: operations["dismiss_inbox__item_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_leads_get"];
        put?: never;
        /** Create Lead */
        post: operations["create_lead_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Lead
         * @description Kéo-thả kanban đổi `stage`.
         */
        patch: operations["update_lead_leads__lead_id__patch"];
        trace?: never;
    };
    "/leads/{lead_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lead Messages */
        get: operations["list_lead_messages_leads__lead_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Crm Messages */
        get: operations["list_crm_messages_crm_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crm-messages/{message_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Crm Message
         * @description Nút "Gửi trả lời này" — chủ duyệt từng tin, không có gửi hàng loạt tự động.
         */
        post: operations["send_crm_message_crm_messages__message_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description 3 stat card ở tab Báo cáo, kèm ▲ so kỳ trước.
         */
        get: operations["summary_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attribution
         * @description Khối "Khách đến tiệm từ kênh nào".
         */
        get: operations["attribution_analytics_attribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeseries
         * @description Bar chart 4 tuần.
         */
        get: operations["timeseries_analytics_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscription */
        get: operations["get_subscription_billing_subscription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invoices */
        get: operations["list_invoices_billing_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyticsSummary
         * @description Đo bằng khách hỏi giá / khách đến tiệm / khách quay lại — không phải like/reach.
         */
        AnalyticsSummary: {
            /** Price Inquiries */
            price_inquiries: number;
            /** Walk Ins */
            walk_ins: number;
            /** Returning Customers */
            returning_customers: number;
            /** Published Posts */
            published_posts: number;
            /** New Leads */
            new_leads: number;
            /** Lead Won Rate */
            lead_won_rate: number;
            /** Change Vs Previous Period */
            change_vs_previous_period?: {
                [key: string]: number;
            };
        };
        /** AnalyticsTimeseries */
        AnalyticsTimeseries: {
            /** Metric */
            metric: string;
            /** Points */
            points: components["schemas"]["TimeseriesPoint"][];
        };
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Scheduled At
             * @description Bỏ trống để Havi chọn khung giờ vàng.
             */
            scheduled_at?: string | null;
        };
        /**
         * BrandProfile
         * @description Input bắt buộc cho mọi prompt chế bản — worker đọc từ đây, không hardcode.
         */
        BrandProfile: {
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            industry: components["schemas"]["Industry"];
            /**
             * Tone
             * @default
             * @example thân thiện, gần gũi
             */
            tone: string;
            /**
             * Banned Claims
             * @example [
             *       "chắc chắn tăng giá",
             *       "cam kết 100%"
             *     ]
             */
            banned_claims?: string[];
            /** Faq */
            faq?: components["schemas"]["FaqEntry"][];
            /** Logo Url */
            logo_url?: string | null;
            /** Brand Colors */
            brand_colors?: string[];
        };
        /** BrandProfileUpdate */
        BrandProfileUpdate: {
            /** Tone */
            tone?: string | null;
            /** Banned Claims */
            banned_claims?: string[] | null;
            /** Faq */
            faq?: components["schemas"]["FaqEntry"][] | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Brand Colors */
            brand_colors?: string[] | null;
        };
        /** BulkApproveFailure */
        BulkApproveFailure: {
            /**
             * Content Item Id
             * Format: uuid
             */
            content_item_id: string;
            /** Reason */
            reason: string;
        };
        /**
         * BulkApproveRequest
         * @description Nút "Duyệt & đăng hết" trên thanh duyệt nhanh.
         */
        BulkApproveRequest: {
            /** Content Item Ids */
            content_item_ids: string[];
        };
        /** BulkApproveResult */
        BulkApproveResult: {
            /** Approved */
            approved: string[];
            /** Rejected */
            rejected: components["schemas"]["BulkApproveFailure"][];
        };
        /**
         * CalendarDay
         * @description Lịch là view trên content_item.scheduled_at, không phải bảng riêng.
         */
        CalendarDay: {
            /**
             * Date
             * @example 2026-08-03
             */
            date: string;
            /** Items */
            items: components["schemas"]["ContentItem"][];
        };
        /** CalendarView */
        CalendarView: {
            /** Days */
            days: components["schemas"]["CalendarDay"][];
        };
        /**
         * Channel
         * @description Kênh đầu ra của content — mỗi kênh 1 adapter, lõi AI không biết kênh.
         * @enum {string}
         */
        Channel: "facebook_page" | "google_business" | "zalo_oa" | "reels" | "tiktok" | "youtube" | "email";
        /** ChannelAttribution */
        ChannelAttribution: {
            channel: components["schemas"]["Channel"];
            /** Customers */
            customers: number;
            /** Share */
            share: number;
            /** Note */
            note?: string | null;
        };
        /**
         * ConnectionStatus
         * @enum {string}
         */
        ConnectionStatus: "connected" | "expired" | "revoked";
        /** ContentItem */
        ContentItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Job Id */
            job_id: string | null;
            channel: components["schemas"]["Channel"];
            /**
             * Kind
             * @example Bài ảnh
             * @example Bài đánh giá
             * @example Video ngắn
             */
            kind: string;
            /** Text */
            text: string;
            /** Media Note */
            media_note?: string | null;
            status: components["schemas"]["ContentStatus"];
            /**
             * Version No
             * @default 1
             */
            version_no: number;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ContentItemUpdate
         * @description Sửa text tạo version mới, không ghi đè.
         */
        ContentItemUpdate: {
            /** Text */
            text?: string | null;
            /** Media Note */
            media_note?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
        };
        /** ContentItemVersion */
        ContentItemVersion: {
            /**
             * Content Item Id
             * Format: uuid
             */
            content_item_id: string;
            /** Version No */
            version_no: number;
            /** Text */
            text: string;
            /** Edited By */
            edited_by: string | null;
            /**
             * Edited At
             * Format: date-time
             */
            edited_at: string;
        };
        /** ContentJob */
        ContentJob: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            status: components["schemas"]["ContentJobStatus"];
            /** Raw Inputs */
            raw_inputs: components["schemas"]["RawInput"][];
            /** Content Item Ids */
            content_item_ids?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ContentJobCreate
         * @description Nút "Để Havi viết cho chị" — 1 job, 1 lần gọi LLM, nhiều đầu ra.
         */
        ContentJobCreate: {
            /** Raw Inputs */
            raw_inputs: components["schemas"]["RawInput"][];
        };
        /**
         * ContentJobStatus
         * @enum {string}
         */
        ContentJobStatus: "queued" | "processing" | "drafts_ready" | "failed";
        /**
         * ContentStatus
         * @enum {string}
         */
        ContentStatus: "draft" | "pending_approval" | "approved" | "scheduled" | "publishing" | "published" | "failed" | "dead_letter";
        /**
         * CrmChannel
         * @enum {string}
         */
        CrmChannel: "zalo" | "email";
        /** CrmMessage */
        CrmMessage: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            channel: components["schemas"]["CrmChannel"];
            /** Draft Text */
            draft_text: string;
            status: components["schemas"]["CrmMessageStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CrmMessageStatus
         * @enum {string}
         */
        CrmMessageStatus: "pending_approval" | "sent";
        /** CurrentUser */
        CurrentUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email?: string | null;
            /** Active Workspace Id */
            active_workspace_id?: string | null;
        };
        /** EmailLoginRequest */
        EmailLoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * FaqEntry
         * @description Chỉ câu chủ đã duyệt sẵn mới được trả lời tự động 24/7.
         */
        FaqEntry: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /**
             * Approved
             * @default false
             */
            approved: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Env */
            env: string;
            /** Version */
            version: string;
        };
        /** InboxItem */
        InboxItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            platform: components["schemas"]["Platform"];
            type: components["schemas"]["InboxItemType"];
            /** Content */
            content: string;
            /** Author Name */
            author_name: string;
            /** Sentiment */
            sentiment?: string | null;
            /** Ai Suggested Reply */
            ai_suggested_reply?: string | null;
            status: components["schemas"]["InboxItemStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * InboxItemStatus
         * @enum {string}
         */
        InboxItemStatus: "new" | "drafted" | "sent";
        /**
         * InboxItemType
         * @enum {string}
         */
        InboxItemType: "comment" | "review" | "message";
        /**
         * InboxReplyRequest
         * @description Không có full_auto: luôn phải bấm gửi.
         */
        InboxReplyRequest: {
            /** Text */
            text: string;
        };
        /**
         * Industry
         * @description 6 ô trong bước 1 của Onboarding.
         * @enum {string}
         */
        Industry: "spa" | "food_beverage" | "real_estate" | "professional" | "online_shop" | "other";
        /** Invoice */
        Invoice: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Amount Vnd */
            amount_vnd: number;
            /** Status */
            status: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
        };
        /** Lead */
        Lead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            source: components["schemas"]["LeadSource"];
            stage: components["schemas"]["LeadStage"];
            reply_status: components["schemas"]["LeadReplyStatus"];
            /** Message */
            message?: string | null;
            /** Suggested Reply */
            suggested_reply?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LeadCreate */
        LeadCreate: {
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            source: components["schemas"]["LeadSource"];
            /** Message */
            message?: string | null;
        };
        /**
         * LeadReplyStatus
         * @description Status pill trên lead card ở tab Khách tiềm năng (HANDOFF State Management).
         *
         *     Tách khỏi LeadStage: đây là trạng thái của câu trả lời, không phải giai đoạn bán hàng.
         * @enum {string}
         */
        LeadReplyStatus: "new" | "auto_replied" | "awaiting_approval" | "sent" | "booked";
        /**
         * LeadSource
         * @enum {string}
         */
        LeadSource: "fanpage" | "maps" | "group" | "crm";
        /**
         * LeadStage
         * @description Pipeline kanban trong Settings/CRM (TECHNICAL_SPEC §8).
         * @enum {string}
         */
        LeadStage: "new" | "contacted" | "qualified" | "won" | "lost";
        /** LeadUpdate */
        LeadUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            stage?: components["schemas"]["LeadStage"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** MediaAsset */
        MediaAsset: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Url */
            url: string;
            type: components["schemas"]["MediaType"];
            /** Tags */
            tags?: string[];
            status: components["schemas"]["MediaStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * MediaStatus
         * @enum {string}
         */
        MediaStatus: "raw" | "used" | "archived";
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "image" | "audio" | "video";
        /** MediaUpdate */
        MediaUpdate: {
            /** Tags */
            tags?: string[] | null;
            status?: components["schemas"]["MediaStatus"] | null;
        };
        /** MediaUploadRequest */
        MediaUploadRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            type: components["schemas"]["MediaType"];
        };
        /**
         * MediaUploadTicket
         * @description Client upload thẳng lên object storage; API chỉ lưu metadata.
         */
        MediaUploadTicket: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Upload Url */
            upload_url: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** OAuthStartResponse */
        OAuthStartResponse: {
            /** Authorization Url */
            authorization_url: string;
            /** State */
            state: string;
        };
        /**
         * OtpChallenge
         * @description Frontend dùng `resend_after_seconds` để chạy đồng hồ đếm ngược trên màn OTP.
         *
         *     `debug_code` chỉ có giá trị khi `HAVI_DEBUG=true` (chưa có provider SMS/Zalo
         *     thật — xem ROADMAP.md "Quyết định cần chốt"). Không log OTP ra bất kỳ đâu.
         */
        OtpChallenge: {
            /** Resend After Seconds */
            resend_after_seconds: number;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Debug Code */
            debug_code?: string | null;
        };
        /**
         * OtpRequest
         * @description SĐT + OTP là kênh chính (qua Zalo/SMS); email + mật khẩu là phụ.
         */
        OtpRequest: {
            /**
             * Phone
             * @example 0901234567
             */
            phone: string;
        };
        /** OtpVerify */
        OtpVerify: {
            /** Phone */
            phone: string;
            /**
             * Code
             * @example 111111
             */
            code: string;
        };
        /** Page[ContentItem] */
        Page_ContentItem_: {
            /** Items */
            items: components["schemas"]["ContentItem"][];
            /** Total */
            total: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** Page[CrmMessage] */
        Page_CrmMessage_: {
            /** Items */
            items: components["schemas"]["CrmMessage"][];
            /** Total */
            total: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** Page[InboxItem] */
        Page_InboxItem_: {
            /** Items */
            items: components["schemas"]["InboxItem"][];
            /** Total */
            total: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** Page[Lead] */
        Page_Lead_: {
            /** Items */
            items: components["schemas"]["Lead"][];
            /** Total */
            total: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** Page[MediaAsset] */
        Page_MediaAsset_: {
            /** Items */
            items: components["schemas"]["MediaAsset"][];
            /** Total */
            total: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /**
         * Plan
         * @description Bảng giá landing page: 0đ 14 ngày / Tiệm Nhỏ 299K / Toàn Diện 599K.
         * @enum {string}
         */
        Plan: "trial" | "tiem_nho" | "toan_dien";
        /**
         * Platform
         * @description Nền tảng có OAuth connection (tập con của Channel).
         * @enum {string}
         */
        Platform: "facebook" | "google_business" | "zalo_oa";
        /**
         * PlatformConnection
         * @description Token mã hoá bằng TOKEN_ENCRYPTION_KEY — không bao giờ xuất ra response.
         */
        PlatformConnection: {
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            platform: components["schemas"]["Platform"];
            status: components["schemas"]["ConnectionStatus"];
            /** Account Name */
            account_name?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Connected By */
            connected_by?: string | null;
        };
        /**
         * PublishMode
         * @description Toggle "Chế độ đăng bài", lưu theo workspace. Không áp dụng cho reply khách.
         * @enum {string}
         */
        PublishMode: "review_first" | "full_auto";
        /** RawInput */
        RawInput: {
            kind: components["schemas"]["RawInputKind"];
            /** Text */
            text?: string | null;
            /** Media Asset Id */
            media_asset_id?: string | null;
        };
        /**
         * RawInputKind
         * @description Chip loại liệu thô trong tab Tạo nội dung.
         * @enum {string}
         */
        RawInputKind: "photo" | "voice" | "text" | "sales_webhook";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RescheduleRequest */
        RescheduleRequest: {
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
        };
        /**
         * SignUpRequest
         * @description Đăng ký chỉ cần tên + SĐT; email/mật khẩu thêm sau trong Cài đặt.
         */
        SignUpRequest: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
        };
        /** Subscription */
        Subscription: {
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            plan: components["schemas"]["Plan"];
            status: components["schemas"]["SubscriptionStatus"];
            /** Current Period End */
            current_period_end?: string | null;
            /**
             * Token Quota Used
             * @default 0
             */
            token_quota_used: number;
            /**
             * Token Quota Limit
             * @default 0
             */
            token_quota_limit: number;
        };
        /**
         * SubscriptionStatus
         * @enum {string}
         */
        SubscriptionStatus: "trialing" | "active" | "past_due" | "canceled";
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /**
             * Period
             * @example 2026-W31
             */
            period: string;
            /** Value */
            value: number;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Active Workspace Id */
            active_workspace_id?: string | null;
            /**
             * Needs Onboarding
             * @default false
             */
            needs_onboarding: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Workspace */
        Workspace: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            industry: components["schemas"]["Industry"];
            plan: components["schemas"]["Plan"];
            publish_mode: components["schemas"]["PublishMode"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
            industry: components["schemas"]["Industry"];
        };
        /** WorkspaceMember */
        WorkspaceMember: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            role: components["schemas"]["WorkspaceRole"];
        };
        /** WorkspaceMemberInvite */
        WorkspaceMemberInvite: {
            /** Phone */
            phone: string;
            /** @default marketer */
            role: components["schemas"]["WorkspaceRole"];
        };
        /**
         * WorkspaceRole
         * @enum {string}
         */
        WorkspaceRole: "owner" | "marketer" | "reviewer" | "sales";
        /** WorkspaceUpdate */
        WorkspaceUpdate: {
            /** Name */
            name?: string | null;
            industry?: components["schemas"]["Industry"] | null;
            publish_mode?: components["schemas"]["PublishMode"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    request_otp_auth_otp_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpChallenge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerify"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_up_auth_sign_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpChallenge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_email_auth_login_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    list_workspaces_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    create_workspace_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workspace_workspaces__workspace_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_workspace_workspaces__workspace_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_workspaces__workspace_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMember"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_member_workspaces__workspace_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMember"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_workspaces__workspace_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_profile_brand_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfile"];
                };
            };
        };
    };
    update_brand_profile_brand_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_media_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["MediaType"] | null;
                status?: components["schemas"]["MediaStatus"] | null;
                tag?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MediaAsset_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_ticket_media_upload_ticket_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadTicket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_media_media__asset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAsset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_content_job_content_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_job_content_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_content_content_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ContentStatus"] | null;
                channel?: components["schemas"]["Channel"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ContentItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_content__content_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_content_content__content_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_content__content_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_content_content__content_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_content_content__content_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_all_content_approve_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApproveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_calendar_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reschedule_calendar__content_id__reschedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformConnection"][];
                };
            };
        };
    };
    start_oauth_connections__platform__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["schemas"]["Platform"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_callback_connections__platform__callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                platform: components["schemas"]["Platform"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformConnection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_connections__platform__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: components["schemas"]["Platform"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inbox_inbox_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["InboxItemStatus"] | null;
                platform?: components["schemas"]["Platform"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InboxItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_reply_inbox__item_id__reply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_inbox__item_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_leads_get: {
        parameters: {
            query?: {
                stage?: components["schemas"]["LeadStage"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Lead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lead_messages_leads__lead_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrmMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crm_messages_crm_messages_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CrmMessageStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CrmMessage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_crm_message_crm_messages__message_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrmMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_analytics_summary_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attribution_analytics_attribution_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelAttribution"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries_analytics_timeseries_get: {
        parameters: {
            query: {
                metric: string;
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsTimeseries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_billing_subscription_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
        };
    };
    list_invoices_billing_invoices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"][];
                };
            };
        };
    };
}
