"""subscription_and_invoices_tables

Revision ID: 09e487272a30
Revises: d4b1e6905c27
Create Date: 2026-08-14 20:58:45.214637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e487272a30'
down_revision: Union[str, Sequence[str], None] = 'd4b1e6905c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('TRIAL', 'TIEM_NHO', 'TOAN_DIEN', name='plan', native_enum=False), nullable=False),
    sa.Column('amount_vnd', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'VOID', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('gateway_reference', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_workspace_id'), 'invoices', ['workspace_id'], unique=False)
    op.create_index('ix_invoices_workspace_issued', 'invoices', ['workspace_id', 'issued_at'], unique=False)
    op.add_column('workspaces', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('workspaces', sa.Column('paid_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'paid_until')
    op.drop_column('workspaces', 'trial_ends_at')
    op.drop_index('ix_invoices_workspace_issued', table_name='invoices')
    op.drop_index(op.f('ix_invoices_workspace_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
