"""video_render_jobs table

Revision ID: 259c737f4350
Revises: 09e487272a30
Create Date: 2026-08-15 17:43:23.810067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '259c737f4350'
down_revision: Union[str, Sequence[str], None] = '09e487272a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_render_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_aspect_ratio', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RENDERING', 'COMPLETED', 'FAILED', 'CANCELLED', name='videorenderstatus', native_enum=False), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('renderer_engine', sa.Enum('FFMPEG', 'REMOTION', name='videorenderengine', native_enum=False), nullable=False),
    sa.Column('source_media_id', sa.Uuid(), nullable=True),
    sa.Column('edit_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_media_id', sa.Uuid(), nullable=True),
    sa.Column('output_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['output_media_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['source_media_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_render_jobs_created_at', 'video_render_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_render_jobs_workspace_id'), 'video_render_jobs', ['workspace_id'], unique=False)
    op.create_index('ix_video_render_jobs_workspace_status', 'video_render_jobs', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_render_jobs_workspace_status', table_name='video_render_jobs')
    op.drop_index(op.f('ix_video_render_jobs_workspace_id'), table_name='video_render_jobs')
    op.drop_index('ix_video_render_jobs_created_at', table_name='video_render_jobs')
    op.drop_table('video_render_jobs')
    # ### end Alembic commands ###
