"""content jobs items versions

Revision ID: 32712ea2080b
Revises: a974c194ff2c
Create Date: 2026-08-08 01:56:10.653856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32712ea2080b'
down_revision: Union[str, Sequence[str], None] = 'a974c194ff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'DRAFTS_READY', 'FAILED', name='contentjobstatus', native_enum=False), nullable=False),
    sa.Column('raw_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_content_jobs_idempotency')
    )
    op.create_index(op.f('ix_content_jobs_workspace_id'), 'content_jobs', ['workspace_id'], unique=False)
    op.create_index('ix_content_jobs_workspace_status', 'content_jobs', ['workspace_id', 'status'], unique=False)
    op.create_table('content_items',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('FACEBOOK_PAGE', 'GOOGLE_BUSINESS', 'ZALO_OA', 'REELS', 'TIKTOK', 'YOUTUBE', 'EMAIL', name='channel', native_enum=False), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('media_note', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'DEAD_LETTER', name='contentstatus', native_enum=False), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_job_id'), 'content_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_content_items_workspace_id'), 'content_items', ['workspace_id'], unique=False)
    op.create_index('ix_content_items_workspace_scheduled', 'content_items', ['workspace_id', 'scheduled_at'], unique=False)
    op.create_index('ix_content_items_workspace_status', 'content_items', ['workspace_id', 'status'], unique=False)
    op.create_table('content_item_versions',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'version_no', name='uq_content_item_versions_no')
    )
    op.create_index(op.f('ix_content_item_versions_content_item_id'), 'content_item_versions', ['content_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_item_versions_content_item_id'), table_name='content_item_versions')
    op.drop_table('content_item_versions')
    op.drop_index('ix_content_items_workspace_status', table_name='content_items')
    op.drop_index('ix_content_items_workspace_scheduled', table_name='content_items')
    op.drop_index(op.f('ix_content_items_workspace_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_job_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index('ix_content_jobs_workspace_status', table_name='content_jobs')
    op.drop_index(op.f('ix_content_jobs_workspace_id'), table_name='content_jobs')
    op.drop_table('content_jobs')
    # ### end Alembic commands ###
