"""event_log provider column

Revision ID: 43eff08a8b58
Revises: b7f77094b946
Create Date: 2026-08-09 15:56:36.063400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43eff08a8b58'
down_revision: Union[str, Sequence[str], None] = 'b7f77094b946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_log', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_log', 'provider')
    # ### end Alembic commands ###
