"""Tầng organizations phía trên workspaces — multi-brand / multi-branch

Thêm một tầng LÊN TRÊN thay vì thêm `brand_id`/`branch_id` vào từng bảng: một
workspace đã là một thương hiệu hoặc chi nhánh, và mười hai bảng nghiệp vụ đều
đã scope theo `workspace_id` với bộ test cách ly tenant đầy đủ. Không bảng nghiệp
vụ nào bị đụng tới ở đây.

Backfill: mỗi workspace đang có được gom vào một tổ chức mang tên chính nó, chủ
sở hữu là chủ workspace. Nhờ vậy dữ liệu cũ không có hàng nào `organization_id`
rỗng, và câu truy vấn "các thương hiệu của tôi" cho kết quả đúng ngay từ ngày
đầu — thay vì phải xử lý riêng nhánh NULL ở mọi chỗ đọc.

Revision ID: 4ec349283cb1
Revises: 97c876429449
Create Date: 2026-08-25 17:15:18.123667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec349283cb1'
down_revision: Union[str, Sequence[str], None] = '97c876429449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='organizationrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_members_org_user')
    )
    op.create_index('ix_org_members_user', 'organization_members', ['user_id'], unique=False)
    op.add_column('workspaces', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'])

    # --- Backfill ---------------------------------------------------------
    #
    # Gom mỗi workspace hiện có vào một tổ chức của riêng nó. Người dùng đơn lẻ
    # sẽ không bao giờ thấy tầng này; nó chỉ có mặt để khi họ mở thương hiệu thứ
    # hai thì không phải migrate gì nữa.
    op.execute(
        """
        INSERT INTO organizations (id, name, owner_user_id, created_at)
        SELECT gen_random_uuid(), w.name, w.owner_user_id, now()
        FROM workspaces w
        WHERE w.organization_id IS NULL
        """
    )
    op.execute(
        """
        UPDATE workspaces w
        SET organization_id = o.id
        FROM organizations o
        WHERE w.organization_id IS NULL
          AND o.owner_user_id = w.owner_user_id
          AND o.name = w.name
        """
    )
    # Chủ workspace là chủ tổ chức tương ứng.
    op.execute(
        """
        INSERT INTO organization_members (organization_id, user_id, role, created_at)
        SELECT o.id, o.owner_user_id, 'OWNER', now()
        FROM organizations o
        ON CONFLICT DO NOTHING
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_column('workspaces', 'organization_id')
    op.drop_index('ix_org_members_user', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
