"""crm_nudges table

Revision ID: 73e510416ffa
Revises: 259c737f4350
Create Date: 2026-08-15 18:04:17.601723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e510416ffa'
down_revision: Union[str, Sequence[str], None] = '259c737f4350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_nudges',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('nudge_type', sa.Enum('INACTIVE_30_DAYS', 'FOLLOWUP_14_DAYS', 'BIRTHDAY_SPECIAL', name='crmnudgetype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'SENT', 'DISMISSED', name='crmmessagestatus', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_nudges_lead_id'), 'crm_nudges', ['lead_id'], unique=False)
    op.create_index(op.f('ix_crm_nudges_status'), 'crm_nudges', ['status'], unique=False)
    op.create_index(op.f('ix_crm_nudges_workspace_id'), 'crm_nudges', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_nudges_workspace_id'), table_name='crm_nudges')
    op.drop_index(op.f('ix_crm_nudges_status'), table_name='crm_nudges')
    op.drop_index(op.f('ix_crm_nudges_lead_id'), table_name='crm_nudges')
    op.drop_table('crm_nudges')
    # ### end Alembic commands ###
