"""Đồng bộ bảng video với model — vá drift do lượt đổi tên bảng để lại

`alembic upgrade head` chạy được nhưng `alembic check` đỏ: migration đổi tên
`video_render_jobs` → `video_posts` đã đổi tên bảng và hai index khai trong
`__table_args__`, nhưng **bỏ sót các index Postgres tự tạo từ `index=True`** —
chúng vẫn mang tên bảng cũ. Cột `scheduled_at`/`settled_at` cũng lệch kiểu vì
model quên `DateTime(timezone=True)` mà cả repo dùng.

Hậu quả nếu không vá: một môi trường dựng mới từ model và một môi trường nâng
cấp dần sẽ có schema khác nhau — đúng loại khác biệt chỉ lộ ra ở production.

Revision ID: 9504b9db3faf
Revises: b2c3d4e5f6a7
Create Date: 2026-08-25 16:22:35.366162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9504b9db3faf'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_posts', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # RENAME chứ không drop-rồi-create: giữa hai lệnh đó bảng không có index,
    # và trên bảng đã có dữ liệu thì mọi truy vấn theo workspace_id phải quét
    # toàn bảng cho tới khi lệnh thứ hai xong.
    op.execute(
        "ALTER INDEX ix_video_render_jobs_workspace_id "
        "RENAME TO ix_video_posts_workspace_id"
    )

    op.alter_column('video_publish_attempts', 'channel',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('FACEBOOK_PAGE', 'GOOGLE_BUSINESS', 'ZALO_OA', 'REELS', 'TIKTOK', 'YOUTUBE', 'EMAIL', name='channel', native_enum=False),
               existing_nullable=False)
    op.alter_column('video_publish_attempts', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('PENDING', 'PUBLISHED', 'FAILED', 'AMBIGUOUS', name='videopublishattemptstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('video_publish_attempts', 'failure_kind',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('TEMPORARY', 'AMBIGUOUS_OUTCOME', 'AUTH_PERMISSION', 'VALIDATION_PERMANENT', name='publishfailurekind', native_enum=False),
               existing_nullable=True)
    op.alter_column('video_publish_attempts', 'settled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.execute(
        "ALTER INDEX ix_video_publish_attempts_video_render_job_id "
        "RENAME TO ix_video_publish_attempts_video_post_id"
    )

    op.create_index(op.f('ix_video_publish_attempts_workspace_id'), 'video_publish_attempts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_publish_attempts_workspace_id'), table_name='video_publish_attempts')
    op.drop_index(op.f('ix_video_publish_attempts_video_post_id'), table_name='video_publish_attempts')
    op.create_index(op.f('ix_video_publish_attempts_video_render_job_id'), 'video_publish_attempts', ['video_post_id'], unique=False)
    op.alter_column('video_publish_attempts', 'settled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('video_publish_attempts', 'failure_kind',
               existing_type=sa.Enum('TEMPORARY', 'AMBIGUOUS_OUTCOME', 'AUTH_PERMISSION', 'VALIDATION_PERMANENT', name='publishfailurekind', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('video_publish_attempts', 'status',
               existing_type=sa.Enum('PENDING', 'PUBLISHED', 'FAILED', 'AMBIGUOUS', name='videopublishattemptstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('video_publish_attempts', 'channel',
               existing_type=sa.Enum('FACEBOOK_PAGE', 'GOOGLE_BUSINESS', 'ZALO_OA', 'REELS', 'TIKTOK', 'YOUTUBE', 'EMAIL', name='channel', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_video_posts_workspace_id'), table_name='video_posts')
    op.create_index(op.f('ix_video_render_jobs_workspace_id'), 'video_posts', ['workspace_id'], unique=False)
    op.alter_column('video_posts', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
