"""Bỏ tầng Goal / Roadmap / Evidence — ngoài phạm vi sản phẩm

Havi quản trị **hệ thống social** của khách, không quản trị **mục tiêu kinh
doanh** của khách. Bốn bảng này (`goals`, `roadmaps`, `roadmap_tasks`,
`evidence_logs`) thuộc vế thứ hai.

Chúng từng là định vị chính ("Universal Goal-to-Roadmap Execution OS", chốt
2026-08-23) rồi bị đảo lại ngày 2026-08-25. Dấu hiệu rõ nhất cho thấy hướng đó
sai: ba màn hình tương ứng chưa bao giờ có mặt trong thanh điều hướng — chính
người viết ra chúng đã đẩy chúng ra rìa. Người dùng mở Havi để đưa một bài lên
Trang, không để quản trị lộ trình.

`downgrade()` dựng lại schema rỗng chứ **không** khôi phục dữ liệu. Bảng đã drop
là mất dữ liệu; sao lưu trước khi chạy ở môi trường có dữ liệu thật.

Revision ID: 97c876429449
Revises: 9504b9db3faf
Create Date: 2026-08-25 16:48:41.667868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97c876429449'
down_revision: Union[str, Sequence[str], None] = '9504b9db3faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Thứ tự drop đi từ bảng con lên bảng cha. Autogenerate xếp `roadmaps`
    # trước `roadmap_tasks`, và Postgres từ chối vì khoá ngoại còn trỏ tới.
    #
    #   evidence_logs ─┐
    #   roadmap_reviews┤→ roadmap_tasks → roadmaps → goals
    #
    for table in ("evidence_logs", "roadmap_reviews", "roadmap_tasks", "roadmaps", "goals"):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('roadmap_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('why_this_is_next', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time_estimate_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('capability_module', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('inputs_needed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('done_rule', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fallback_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('evidence_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('roadmap_tasks_goal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('roadmap_tasks_roadmap_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('roadmap_tasks_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_tasks_pkey'))
    )
    op.create_index(op.f('ix_roadmap_tasks_workspace_id'), 'roadmap_tasks', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_roadmap_tasks_status'), 'roadmap_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_roadmap_tasks_scheduled_date'), 'roadmap_tasks', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_roadmap_tasks_roadmap_id'), 'roadmap_tasks', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_tasks_goal_id'), 'roadmap_tasks', ['goal_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('evidence_definition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('target_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('weekly_capacity_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('constraints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('goals_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('goals_pkey'))
    )
    op.create_index(op.f('ix_goals_workspace_id'), 'goals', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('horizon_90d', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('horizon_30d', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('horizon_7d', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assumptions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('roadmaps_goal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('roadmaps_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmaps_pkey'))
    )
    op.create_index(op.f('ix_roadmaps_workspace_id'), 'roadmaps', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_status'), 'roadmaps', ['status'], unique=False)
    op.create_index(op.f('ix_roadmaps_goal_id'), 'roadmaps', ['goal_id'], unique=False)
    op.create_table('evidence_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('evidence_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('media_asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('evidence_logs_goal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('evidence_logs_media_asset_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['roadmap_tasks.id'], name=op.f('evidence_logs_task_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('evidence_logs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_logs_pkey'))
    )
    op.create_index(op.f('ix_evidence_logs_workspace_id'), 'evidence_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_evidence_logs_task_id'), 'evidence_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_evidence_logs_goal_id'), 'evidence_logs', ['goal_id'], unique=False)
    op.create_table('roadmap_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('roadmap_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('obstacles_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('replan_diff', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('roadmap_reviews_goal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('roadmap_reviews_roadmap_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('roadmap_reviews_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('roadmap_reviews_pkey'))
    )
    op.create_index(op.f('ix_roadmap_reviews_workspace_id'), 'roadmap_reviews', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_roadmap_reviews_roadmap_id'), 'roadmap_reviews', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_reviews_goal_id'), 'roadmap_reviews', ['goal_id'], unique=False)
    # ### end Alembic commands ###
