"""media_assets table

Revision ID: a974c194ff2c
Revises: eb7685b1cb83
Create Date: 2026-08-08 01:48:13.479157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a974c194ff2c'
down_revision: Union[str, Sequence[str], None] = 'eb7685b1cb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'AUDIO', 'VIDEO', name='mediatype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RAW', 'USED', 'ARCHIVED', name='mediastatus', native_enum=False), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_media_assets_workspace_id'), 'media_assets', ['workspace_id'], unique=False)
    op.create_index('ix_media_assets_workspace_status', 'media_assets', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_assets_workspace_status', table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_workspace_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
