"""platform connections and publish jobs

Revision ID: b7f77094b946
Revises: 6cb25077be10
Create Date: 2026-08-08 13:45:25.471371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f77094b946'
down_revision: Union[str, Sequence[str], None] = '6cb25077be10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_connections',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('FACEBOOK', 'GOOGLE_BUSINESS', 'ZALO_OA', name='platform', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'EXPIRED', 'REVOKED', name='connectionstatus', native_enum=False), nullable=False),
    sa.Column('access_token_encrypted', sa.String(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('external_account_id', sa.String(), nullable=True),
    sa.Column('connected_by', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', name='uq_connection_workspace_platform')
    )
    op.create_index(op.f('ix_platform_connections_workspace_id'), 'platform_connections', ['workspace_id'], unique=False)
    op.create_table('publish_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('FACEBOOK_PAGE', 'GOOGLE_BUSINESS', 'ZALO_OA', 'REELS', 'TIKTOK', 'YOUTUBE', 'EMAIL', name='channel', native_enum=False), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_FLIGHT', 'SUCCEEDED', 'FAILED', 'DEAD_LETTER', name='publishstatus', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_post_id', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_kind', sa.Enum('TEMPORARY', 'AUTH_PERMISSION', 'VALIDATION_PERMANENT', name='publishfailurekind', native_enum=False), nullable=True),
    sa.Column('failure_detail', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_publish_jobs_idempotency_key')
    )
    op.create_index(op.f('ix_publish_jobs_content_item_id'), 'publish_jobs', ['content_item_id'], unique=False)
    op.create_index('ix_publish_jobs_status_scheduled', 'publish_jobs', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_publish_jobs_workspace_id'), 'publish_jobs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publish_jobs_workspace_id'), table_name='publish_jobs')
    op.drop_index('ix_publish_jobs_status_scheduled', table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_content_item_id'), table_name='publish_jobs')
    op.drop_table('publish_jobs')
    op.drop_index(op.f('ix_platform_connections_workspace_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    # ### end Alembic commands ###
