"""leads revenue_vnd and order_id columns

Revision ID: b9d9c3205605
Revises: 73e510416ffa
Create Date: 2026-08-15 20:54:13.835184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d9c3205605'
down_revision: Union[str, Sequence[str], None] = '73e510416ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('revenue_vnd', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leads', sa.Column('order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'order_id')
    op.drop_column('leads', 'revenue_vnd')
    # ### end Alembic commands ###
