"""init user workspace brand_profile event_log

Revision ID: c5a2a7713af1
Revises: 
Create Date: 2026-08-08 00:38:25.733793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5a2a7713af1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('job_kind', sa.String(), nullable=False),
    sa.Column('input_summary', sa.String(), nullable=False),
    sa.Column('output_summary', sa.String(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_log_workspace_created', 'event_log', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_log_workspace_id'), 'event_log', ['workspace_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_index('ix_otp_challenges_phone_expires', 'otp_challenges', ['phone', 'expires_at'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('active_workspace_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.Enum('SPA', 'FOOD_BEVERAGE', 'REAL_ESTATE', 'PROFESSIONAL', 'ONLINE_SHOP', 'OTHER', name='industry', native_enum=False), nullable=False),
    sa.Column('plan', sa.Enum('TRIAL', 'TIEM_NHO', 'TOAN_DIEN', name='plan', native_enum=False), nullable=False),
    sa.Column('publish_mode', sa.Enum('REVIEW_FIRST', 'FULL_AUTO', name='publishmode', native_enum=False), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_profiles',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('industry', sa.Enum('SPA', 'FOOD_BEVERAGE', 'REAL_ESTATE', 'PROFESSIONAL', 'ONLINE_SHOP', 'OTHER', name='industry', native_enum=False), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('banned_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('brand_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MARKETER', 'REVIEWER', 'SALES', name='workspacerole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_members')
    op.drop_table('brand_profiles')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_otp_challenges_phone_expires', table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_event_log_workspace_id'), table_name='event_log')
    op.drop_index('ix_event_log_workspace_created', table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
