"""email as primary identity, phone optional

Revision ID: eb7685b1cb83
Revises: c5a2a7713af1
Create Date: 2026-08-08 01:20:12.611867

CẢNH BÁO: migration này chỉ chạy được trên database TRỐNG. Nó thêm
`otp_challenges.email` NOT NULL không có server_default, và đổi `users.email`
sang NOT NULL — cả hai sẽ fail nếu đã có row. An toàn ở thời điểm viết vì chưa
mời beta (ROADMAP.md "Hạ tầng bắt buộc trước beta" chưa đạt), nhưng nếu cần
chạy lại trên DB đã có dữ liệu thì phải viết lại thành multi-step: thêm cột
nullable → backfill → mới set NOT NULL.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7685b1cb83'
down_revision: Union[str, Sequence[str], None] = 'c5a2a7713af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_challenges', sa.Column('email', sa.String(), nullable=False))
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_phone_expires'), table_name='otp_challenges')
    op.create_index(op.f('ix_otp_challenges_email'), 'otp_challenges', ['email'], unique=False)
    op.create_index('ix_otp_challenges_email_expires', 'otp_challenges', ['email', 'expires_at'], unique=False)
    op.drop_column('otp_challenges', 'phone')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('otp_challenges', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_otp_challenges_email_expires', table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_email'), table_name='otp_challenges')
    op.create_index(op.f('ix_otp_challenges_phone_expires'), 'otp_challenges', ['phone', 'expires_at'], unique=False)
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.drop_column('otp_challenges', 'email')
    # ### end Alembic commands ###
